### PR TITLE
Dockerizing latest for Apple M1 Silicon

### PR DESCRIPTION
**Pull request by daithi-coombes**
related issue: https://github.com/crytic/slither/issues/937

### CODE REVIEW

**Comment by daithi-coombes** [comment]
Some issues with Github Actions:

```
  slither --help
  shell: sh -e {0}
Traceback (most recent call last):
  File "/home/slither/.local/bin/slither", line 33, in <module>
    sys.exit(load_entry_point('slither-analyzer==0.8.1', 'console_scripts', 'slither')())
  File "/home/slither/.local/bin/slither", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/local/lib/python3.8/importlib/metadata.py", line 503, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/local/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: slither-analyzer
Error: Process completed with exit code 1.
```

Related yaml:
```yaml
  sec-slither:
    runs-on: ubuntu-latest
    container:
      image: daithi/slither:latest
    steps:
      - uses: actions/checkout@master
      - run: echo "${HOME}/.local/bin" >> $GITHUB_PATH
      - run: slither --help
```

`docker run --rm daithi/slither slither --help` works
testing the gh yaml with [act](https://github.com/nektos/act) also works.

I'm thinking maybe some linking is missing. `$HOME/.local/bin` is in the path (checked also in gh workflow) but doesn't have `slither-analyzer`

**Comment by montyly** [comment]
@elopez : can you take a look at this? I haven't followed the progress on M1, and I am not sure we still need to update this

**Comment by elopez** [comment]
Hey @montyly! Slither hasn't had Docker images built for a while as far as I can tell (last I see is ~3y ago, and the slither README suggests using eth-security-toolbox and not this dockerfile), so I don't know if anyone is using this 🤔

Personally I'd prefer to not to build Python from scratch as it is done in this PR, as that involves adding extra dependencies and build products which make the image heavier and the dockerfile more complex. Updating the base image to a modern ubuntu (like 20.04 or 22.04) so that we have newer python (and maybe adding some build tools for pysha3) should be enough to get M1 going.

NB: solc is also not available for aarch64 linux, I'm guessing this dockerfile would only work on M1 Macs with the emulation, and not real linux aarch64. If we're revamping this dockerfile, it might be a good time to use solc-select instead of an old solc binary 😄

**Comment by montyly** [comment]
I agree with @elopez , let's simplify our docker and switch to solc-select (https://github.com/crytic/slither/issues/1330).

Thanks [daithi-coombes](https://github.com/daithi-coombes) for the work; we will do the improvements in a separate PR

**Pull request closed without merging**
