### PR TITLE
Dev Addresses Feature Request #1202

### PR DESCRIPTION
**Pull request by man715**
@0xalpharush responded to feature request https://github.com/crytic/slither/issues/1202 suggesting to start of with identifying functions that use msg.data similar to the way msg.sender and msg.gas is being identified. 
That step of the feature request is implemented in this PR.

### CODE REVIEW

**Comment by 0xalpharush** [comment]
@man715 can you sign the CLA?

**Comment by man715** [comment]
I think I did but it was after I sent the PR.

**Comment by montyly** [comment]
Hi [man715](https://github.com/man715). Thanks for the work. 

It looks like you used two different emails for the commit, and one of them was not used to sign the CLA - as a result we can merge the PR.
Could you sign the CLA with the second email?

**Comment by man715** [comment]
It looks like one of the commits was associated with man715@webhack.localdomain which is not a real email address. (Not sure why I had it set up that way.)

**Comment by 0xalpharush** [comment]
@man715 bump

**Pull request closed without merging**
