### PR TITLE
[WIP] Open source middle

### PR DESCRIPTION
**Pull request by montyly**
This PR open source middle. It is the work of @aaronyoo and @pgoodman.

Require:
```
pip3 install graphviz
```
And `tkinter`. On ubuntu:
```
sudo apt-get install python3-tk
```

Currently it does not work. For example running
```
slither-middle slither/tools/middle/tests/demo.sol
```
Give me this error:
```
framework/gui.py", line 181, in __init__
    hbar_source.pack(side=tk.BOTTOM, fill=tk.X)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2387, in pack_configure
    self.tk.call(
_tkinter.TclError: cannot use geometry manager pack inside .!notebook.!frame.!frame2 which already has slaves managed by grid
```

Checklist to have this PR merged:

- [ ] Have slither-middle working
- [ ] Improve the `main` function: add flags and a help menu
- [ ] Pass our CI
- [ ] Add `tkinter` install instruction for macos and Windows

### CODE REVIEW

**Comment by roddux** [comment]
Okay, I've worked around the Tkinter complains by commenting out the offending lines. Functionality seems the same, but might want a comb-over by someone more experienced with the codebase. Also fixed some API calls; `BinaryType.str()` is now just `str()`.

**Comment by aaronyoo** [comment]
> Okay, I've worked around the Tkinter complains by commenting out the offending lines. Functionality seems the same, but might want a comb-over by someone more experienced with the codebase. Also fixed some API calls; `BinaryType.str()` is now just `str()`.

I can look at these changes. Sometime probably in the next few days. Its been awhile so I will need to spin back up.

**Comment by aaronyoo** [comment]
Just wanted to update that I haven't forgotten about this 😄 . Things got a bit busy at work last week. Should get some time this week to work on this though.

**Comment by montyly** [comment]
I am closing this PR since no progress has been made since 2021.

**Pull request closed without merging**
