### PR TITLE
fixed: pausable printer includes checks on constructor()

### PR DESCRIPTION
**Pull request by aga7hokakological**
This PR is related to the issue #1671 where when pausable is run then it also shows the constructor/view/pure function. This PR fixes that.

### CODE REVIEW

**Comment by 0xalpharush** [comment]
Would you make your pull request against the `dev` branch please?

**Comment by aga7hokakological** [comment]
Okay did it.

**Review by devtooligan — APPROVED** [review]
lgtm! thank you

**Comment by montyly** [comment]
Great, thanks @aga7hokakological

**Pull request merged**
