### PR TITLE
fixed State variables shadowed by a local variable are incorrectly set to the local variable

### LINKED ISSUE #2058: [Bug]: State variables shadowed by a local variable are incorrectly set to the local variable
### Describe the issue:

A state variable is used before it was shadowed. The dependency goes to the local variable instead of state variable

### Code example to reproduce the issue:

```solidity
// SPDX-License-Identifier: UNLICENSED

pragma solidity 0.8.7;

contract B {
    uint public x = 21;
    function a()  public {
        uint u = 2 * x;  // BUG
        uint x;
    }
}
```

```python
> from slither import Slither
>
>
> a = Slither('b.sol').contracts[0].functions[0]
> buggy_node = a.nodes[1]
> print(buggy_node.variables_read[0].canonical_name)
>> B.a().x
```

### Version:

0.9.3
(tested the freshest dev branch 3e390264a4903c522718b33478e5acb735f3e0e6)

### Relevant log output:

_No response_

### PR DESCRIPTION
**Pull request by Tiko7454**
if variables was not seen before, search for it in the state variables

### CODE REVIEW

**Comment by Tiko7454** [comment]
No, it works properly

```python
>>> from slither import Slither
>>> a = Slither('a.sol').contracts[0].functions[0]
>>> a.local_variables
[<slither.core.variables.local_variable.LocalVariable object at 0x7ff15a5ac3d0>, <slither.core.variables.local_variable.LocalVariable object at 0x7ff15af1eb50>]
>>> a.nodes[2].variables_read
[<slither.core.variables.local_variable.LocalVariable object at 0x7ff15af1eb50>]
>>> a.nodes[2].variables_read[0]
<slither.core.variables.local_variable.LocalVariable object at 0x7ff15af1eb50>
>>> print(a.nodes[2].variables_read[0])
x
```

**Comment by 0xalpharush** [comment]
It works for the compact AST because we have the referenced declaration. I'm not sure how to solve this for legacy AST without reworking 

You can try it by removing the pragma: 
`solc-select use 0.7.6 --always-installl && slither example.sol --print declaration   --solc-force-legacy-json`
u references the state variable 
```
# Contracts
# B
        - Declaration: example.sol#5 (10 - 12)
        - Implementation: example.sol#5-11 (1 - 2)
        - References: []

        ## Function
                - B.a()
                        - Declaration: example.sol#7 (14 - 16)
                        - Implementation: example.sol#7-10 (5 - 6)
                        - References: []
                - B.slitherConstructorVariables()
                        - Declaration: example.sol#5-6 (1 - 16)
                        - Implementation: example.sol#5-11 (1 - 2)
                        - References: []

        ## State variables
                - x
                        - Declaration: example.sol#6 (17 - 19)
                        - Implementation: example.sol#6 (5 - 23)
                        - References: ['example.sol#9 (22 - 23)']
```

**Comment by Tiko7454** [comment]
When is legacy json considered as default option?

**Comment by 0xalpharush** [comment]
It is enabled by default for solc 0.4.0 until 0.4.12. Then it must be enabled manually. It was deprecated in 0.8.0

**Comment by montyly** [comment]
I am fine if we don't consider the legacy AST for new fixes moving forward.

In the long term we need to rewrite the solc parsing without the legacy AST to reduce complexity, and keep the current parser as "best effort" for the legacy format

**Comment by 0xalpharush** [comment]
@Tiko7454 We merged https://github.com/crytic/slither/pull/2121 as fix. Thanks for reporting and purposing a fix this issue!

**Pull request closed without merging**
