### PR TITLE
feat: docker improvement

### PR DESCRIPTION
**Pull request by yxliang01**
- install and run as normal user
- copy code from current directory, instead of installing from registry (might not be wanted?)
- add .dockerignore file, only ignores `Dockerfile` currently

### CODE REVIEW

**Comment by yxliang01** [comment]
@montyly I finally remember to come back here and signed the CLA. Is this still relevant or wanted? If not, I can change accordingly or close. :)

**Comment by yxliang01** [comment]
@montyly Possibly you want to process this as well? Since this has been hanging for long 6 months. For some reason the CLA status is not so right?..

**Comment by montyly** [comment]
Hi @yxliang01. 
I am not sure why, but something is wrong with the CLA and I can't merge the PR. Would it be ok for you to close this PR and create a similar one? Thanks!

**Comment by yxliang01** [comment]
@montyly The CLA is working now after closing and reopening. So, just need to wait for the CI :)

**Comment by yxliang01** [comment]
@montyly  :tada: CI passed :)

**Comment by montyly** [comment]
Awesome, thank you @yxliang01 !

**Pull request merged**
