### PR TITLE
Fix detection of library events

### PR DESCRIPTION
**Pull request by medariox**
Fixes https://github.com/crytic/slither/issues/1407

### CODE REVIEW

**Comment by kristovatlas** [comment]
@medariox I'd like to test this branch against my Solidity code. If you have a moment, how would I run this branch's version of slither from the command line vs the one I installed with homebrew? The process is not obvious to me from the README.

**Comment by medariox** [comment]
@kristovatlas 
You can use pip to install the patched version with: `pip install git+https://github.com/medariox/slither.git@patch-1`

**Comment by kristovatlas** [comment]
Thanks. Can confirm that this resolves https://github.com/crytic/slither/issues/1407 with my code base.

**Comment by montyly** [comment]
Thanks @medariox for this fix. I merged it in #1442. We will issue a minor release to include it

**Pull request merged**
