### PR TITLE
Add JSON output functionality for printers

### PR DESCRIPTION
**Pull request by Man-Jain**
This changes the code to return the result as output if --json argument
is passed to printers.

Solves https://github.com/crytic/slither/issues/286

### CODE REVIEW

**Comment by Xenomega** [comment]
Hello @Man-Jain , we appreciate your contribution.

This PR is a good start, but misses the mark a bit, so we would like to request changes. I would focus on improving the following:
- JSON results should be aggregated (combined), so that multiple results (detectors, printers, console output) can be returned in one JSON file. All different result types are put under `results`. For a better example of how this works, check out https://github.com/crytic/slither/pull/266, which will be merged shortly. That PR will return different result types under the `results` JSON node, such as `console`, `detectors`, `detector-types`. It should be a good example of how expected output should generally look.
- The JSON output should not simply be a filename pointing to the data output in traditional non-JSON form. That would overlook the point of adding JSON output, since the filenames are already deterministic. You should instead be outputting the important data the printer provides solely in JSON format.

Hopefully that clears things up a bit! Again, we appreciate you working on this issue. :)

**Comment by Man-Jain** [comment]
Hey Thanks for the feedback. It is really helpful. So this will mean that I'll have to put my patch on top of yours.

**Comment by Xenomega** [comment]
No problem! The output for printers should not go to file in this case. Instead you should find a way to represent the data that _would've_ been output in a file if `--json` wasn't specified, in the JSON itself. 

Example: Lets say you wanted JSON output for inheritance graph, you could simply output the DOT file format encoded in the JSON itself. For the non-graph inheritance printer, you could make a JSON node that has a list of subnodes, where each subnode is a contract, and the subnodes under that point to other contracts they derive from.

That's just an example, but the format is up to you to design. It should be intuitive, concise, and provide all the information you can imagine any external tooling might desire.

**Comment by Man-Jain** [comment]
As per the example you have suggested would require me to change almost all of the printers. It would mean that all of the printers have to be adapted to format the output differently in case of --json is given to it. As for the output of printers some print formatted text, some print tables and some output charts. Wouldn't this be a lot of work for one issue to cover.

**Comment by Man-Jain** [comment]
The code now is able to print the output of a printer to json as it does in case of detector. The code is able to detect the type of output and formats the json in format such that external tools can utilize it. I  have also modified two printers as an example of how this will look. The json looks like [this](https://pastebin.com/feMEB1sX) when both these printers are run simultaneously. The format of the printer itself would depend upon how the printer is implemented.

Do we have a need where we would have to run printer and detectors in a single command. Because that might require going deeper into the codebase. As [this](https://github.com/crytic/slither/blob/master/slither/__main__.py#L71) function implies that only one of them can be run at a time. 

Please review and give your feedback.

Another thing I saw that when giving json-types argument `detector-types` it fails. Is it expected?

**Comment by Man-Jain** [comment]
Waiting for your feedback on this commit so that I can work further.

**Comment by montyly** [comment]
I am closing this PR, as it is replaced by https://github.com/crytic/slither/pull/356

**Pull request closed without merging**
