### PR TITLE
Fix using for global function name collision

### PR DESCRIPTION
**Pull request by 0xalpharush**
Both `SD59x18` and `UD60x18` defined a `mul` function and globally bind the function to the type which wasn't being handled by `_analyze_top_level_function`. I don't think overloading can be done in a using for but that should be investigated.

Fix https://github.com/crytic/slither/issues/1607

### CODE REVIEW

**Comment by PaulRBerg** [comment]
Nope, Solidity doesn't support overloading functions in the `using for ... global` directive. I have actually [requested this as a feature](https://forum.soliditylang.org/t/permit-overloaded-methods-for-user-defined-value-types/987/3) on the Solidity forum.

Taking this code snippet as an example:

```solidity
pragma solidity >=0.8.17;

type UD60x18 is uint256;

using { foo } for UD60x18;

function foo(UD60x18 x) pure returns (UD60x18 result) {
    result = x;
}

function foo(UD60x18 x, UD60x18 y) pure returns (UD60x18 result) {
    x;
    result = y;
}
```

Will produce this error:

```text
from solidity:
DeclarationError: Identifier not found or not unique.
 --> contracts/Foo.sol:6:9:
  |
6 | using { foo } for UD60x18;
```

**Comment by montyly** [comment]
Can we add a test for this one?

**Comment by montyly** [comment]
Can we add the test to the CI? Do we actually need foundry to run this example?

**Comment by PaulRBerg** [comment]
I'm sorry to chase, but are there any updates here? Is this fix still slated to be included in v0.9.3?

**Comment by 0xalpharush** [comment]
@montyly I added a test. @PaulRBerg This will be included in the upcoming release

**Comment by PaulRBerg** [comment]
Amazing news thank so much ser @0xalpharush!! Given that our audits are slated to start on March 20, I'm glad that we will be able to run Slither until then.

**Pull request merged**
